//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TomCpp {

public class MyCoordinate : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MyCoordinate(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MyCoordinate obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MyCoordinate() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SWIG_ExamplePINVOKE.delete_MyCoordinate(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string CoordinateString {
    set {
      SWIG_ExamplePINVOKE.MyCoordinate_CoordinateString_set(swigCPtr, value);
      if (SWIG_ExamplePINVOKE.SWIGPendingException.Pending) throw SWIG_ExamplePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = SWIG_ExamplePINVOKE.MyCoordinate_CoordinateString_get(swigCPtr);
      if (SWIG_ExamplePINVOKE.SWIGPendingException.Pending) throw SWIG_ExamplePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public MyVector3 X {
    set {
      SWIG_ExamplePINVOKE.MyCoordinate_X_set(swigCPtr, MyVector3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = SWIG_ExamplePINVOKE.MyCoordinate_X_get(swigCPtr);
      MyVector3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new MyVector3(cPtr, false);
      return ret;
    } 
  }

  public MyVector3 Y {
    set {
      SWIG_ExamplePINVOKE.MyCoordinate_Y_set(swigCPtr, MyVector3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = SWIG_ExamplePINVOKE.MyCoordinate_Y_get(swigCPtr);
      MyVector3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new MyVector3(cPtr, false);
      return ret;
    } 
  }

  public MyVector3 Z {
    set {
      SWIG_ExamplePINVOKE.MyCoordinate_Z_set(swigCPtr, MyVector3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = SWIG_ExamplePINVOKE.MyCoordinate_Z_get(swigCPtr);
      MyVector3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new MyVector3(cPtr, false);
      return ret;
    } 
  }

  public MyCoordinate() : this(SWIG_ExamplePINVOKE.new_MyCoordinate__SWIG_0(), true) {
  }

  public MyCoordinate(MyVector3 a, MyVector3 b, MyVector3 c) : this(SWIG_ExamplePINVOKE.new_MyCoordinate__SWIG_1(MyVector3.getCPtr(a), MyVector3.getCPtr(b), MyVector3.getCPtr(c)), true) {
    if (SWIG_ExamplePINVOKE.SWIGPendingException.Pending) throw SWIG_ExamplePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
