//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TomCpp {

public class MyCppClass : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MyCppClass(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MyCppClass obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MyCppClass() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SWIG_ExamplePINVOKE.delete_MyCppClass(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public MyCppClass() : this(SWIG_ExamplePINVOKE.new_MyCppClass(), true) {
  }

  public double Add(double a, double b) {
    double ret = SWIG_ExamplePINVOKE.MyCppClass_Add__SWIG_0(swigCPtr, a, b);
    return ret;
  }

  public MyVector3 CreateVector3() {
    MyVector3 ret = new MyVector3(SWIG_ExamplePINVOKE.MyCppClass_CreateVector3(swigCPtr), true);
    return ret;
  }

  public MyVector3 Cross(MyVector3 a, MyVector3 b) {
    MyVector3 ret = new MyVector3(SWIG_ExamplePINVOKE.MyCppClass_Cross(swigCPtr, MyVector3.getCPtr(a), MyVector3.getCPtr(b)), true);
    if (SWIG_ExamplePINVOKE.SWIGPendingException.Pending) throw SWIG_ExamplePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public MyVector3 Add(MyVector3 a, MyVector3 b) {
    MyVector3 ret = new MyVector3(SWIG_ExamplePINVOKE.MyCppClass_Add__SWIG_1(swigCPtr, MyVector3.getCPtr(a), MyVector3.getCPtr(b)), true);
    if (SWIG_ExamplePINVOKE.SWIGPendingException.Pending) throw SWIG_ExamplePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Vector3Collection GetMyCollection() {
    Vector3Collection ret = new Vector3Collection(SWIG_ExamplePINVOKE.MyCppClass_GetMyCollection(swigCPtr), true);
    return ret;
  }

  public Vector3Collection ShiftMyCollection(Vector3Collection ary) {
    Vector3Collection ret = new Vector3Collection(SWIG_ExamplePINVOKE.MyCppClass_ShiftMyCollection(swigCPtr, Vector3Collection.getCPtr(ary)), true);
    if (SWIG_ExamplePINVOKE.SWIGPendingException.Pending) throw SWIG_ExamplePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void ExpandMyCollection(Vector3Collection ary) {
    SWIG_ExamplePINVOKE.MyCppClass_ExpandMyCollection(swigCPtr, Vector3Collection.getCPtr(ary));
    if (SWIG_ExamplePINVOKE.SWIGPendingException.Pending) throw SWIG_ExamplePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
