//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TomCpp {

public class MyData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MyData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MyData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MyData() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SWIG_ExamplePINVOKE.delete_MyData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string str {
    set {
      SWIG_ExamplePINVOKE.MyData_str_set(swigCPtr, value);
      if (SWIG_ExamplePINVOKE.SWIGPendingException.Pending) throw SWIG_ExamplePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = SWIG_ExamplePINVOKE.MyData_str_get(swigCPtr);
      if (SWIG_ExamplePINVOKE.SWIGPendingException.Pending) throw SWIG_ExamplePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public short int16 {
    set {
      SWIG_ExamplePINVOKE.MyData_int16_set(swigCPtr, value);
    } 
    get {
      short ret = SWIG_ExamplePINVOKE.MyData_int16_get(swigCPtr);
      return ret;
    } 
  }

  public int int32 {
    set {
      SWIG_ExamplePINVOKE.MyData_int32_set(swigCPtr, value);
    } 
    get {
      int ret = SWIG_ExamplePINVOKE.MyData_int32_get(swigCPtr);
      return ret;
    } 
  }

  public float singal {
    set {
      SWIG_ExamplePINVOKE.MyData_singal_set(swigCPtr, value);
    } 
    get {
      float ret = SWIG_ExamplePINVOKE.MyData_singal_get(swigCPtr);
      return ret;
    } 
  }

  public MyData() : this(SWIG_ExamplePINVOKE.new_MyData__SWIG_0(), true) {
  }

  public MyData(double a, string b, short c, int d, float e) : this(SWIG_ExamplePINVOKE.new_MyData__SWIG_1(a, b, c, d, e), true) {
    if (SWIG_ExamplePINVOKE.SWIGPendingException.Pending) throw SWIG_ExamplePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
