//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TomCpp {

public class MyVector3 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MyVector3(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MyVector3 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MyVector3() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SWIG_ExamplePINVOKE.delete_MyVector3(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double X {
    set {
      SWIG_ExamplePINVOKE.MyVector3_X_set(swigCPtr, value);
    } 
    get {
      double ret = SWIG_ExamplePINVOKE.MyVector3_X_get(swigCPtr);
      return ret;
    } 
  }

  public double Y {
    set {
      SWIG_ExamplePINVOKE.MyVector3_Y_set(swigCPtr, value);
    } 
    get {
      double ret = SWIG_ExamplePINVOKE.MyVector3_Y_get(swigCPtr);
      return ret;
    } 
  }

  public double Z {
    set {
      SWIG_ExamplePINVOKE.MyVector3_Z_set(swigCPtr, value);
    } 
    get {
      double ret = SWIG_ExamplePINVOKE.MyVector3_Z_get(swigCPtr);
      return ret;
    } 
  }

  public MyVector3() : this(SWIG_ExamplePINVOKE.new_MyVector3__SWIG_0(), true) {
  }

  public MyVector3(double x, double y, double z) : this(SWIG_ExamplePINVOKE.new_MyVector3__SWIG_1(x, y, z), true) {
  }

}

}
