//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TomCpp {

class SWIG_ExamplePINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="SWIGRegisterExceptionCallbacks_SWIG_Example")]
    public static extern void SWIGRegisterExceptionCallbacks_SWIG_Example(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_SWIG_Example")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_SWIG_Example(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_SWIG_Example(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_SWIG_Example(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="SWIGRegisterStringCallback_SWIG_Example")]
    public static extern void SWIGRegisterStringCallback_SWIG_Example(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_SWIG_Example(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static SWIG_ExamplePINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyVector3_X_set")]
  public static extern void MyVector3_X_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyVector3_X_get")]
  public static extern double MyVector3_X_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyVector3_Y_set")]
  public static extern void MyVector3_Y_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyVector3_Y_get")]
  public static extern double MyVector3_Y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyVector3_Z_set")]
  public static extern void MyVector3_Z_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyVector3_Z_get")]
  public static extern double MyVector3_Z_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_new_MyVector3__SWIG_0")]
  public static extern global::System.IntPtr new_MyVector3__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_new_MyVector3__SWIG_1")]
  public static extern global::System.IntPtr new_MyVector3__SWIG_1(double jarg1, double jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_delete_MyVector3")]
  public static extern void delete_MyVector3(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyData_str_set")]
  public static extern void MyData_str_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyData_str_get")]
  public static extern string MyData_str_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyData_int16_set")]
  public static extern void MyData_int16_set(global::System.Runtime.InteropServices.HandleRef jarg1, short jarg2);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyData_int16_get")]
  public static extern short MyData_int16_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyData_int32_set")]
  public static extern void MyData_int32_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyData_int32_get")]
  public static extern int MyData_int32_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyData_singal_set")]
  public static extern void MyData_singal_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyData_singal_get")]
  public static extern float MyData_singal_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_new_MyData__SWIG_0")]
  public static extern global::System.IntPtr new_MyData__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_new_MyData__SWIG_1")]
  public static extern global::System.IntPtr new_MyData__SWIG_1(double jarg1, string jarg2, short jarg3, int jarg4, float jarg5);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_delete_MyData")]
  public static extern void delete_MyData(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyCoordinate_CoordinateString_set")]
  public static extern void MyCoordinate_CoordinateString_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyCoordinate_CoordinateString_get")]
  public static extern string MyCoordinate_CoordinateString_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyCoordinate_X_set")]
  public static extern void MyCoordinate_X_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyCoordinate_X_get")]
  public static extern global::System.IntPtr MyCoordinate_X_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyCoordinate_Y_set")]
  public static extern void MyCoordinate_Y_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyCoordinate_Y_get")]
  public static extern global::System.IntPtr MyCoordinate_Y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyCoordinate_Z_set")]
  public static extern void MyCoordinate_Z_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyCoordinate_Z_get")]
  public static extern global::System.IntPtr MyCoordinate_Z_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_new_MyCoordinate__SWIG_0")]
  public static extern global::System.IntPtr new_MyCoordinate__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_new_MyCoordinate__SWIG_1")]
  public static extern global::System.IntPtr new_MyCoordinate__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_delete_MyCoordinate")]
  public static extern void delete_MyCoordinate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyStaticClass_ShowMessage")]
  public static extern void MyStaticClass_ShowMessage(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_new_MyStaticClass")]
  public static extern global::System.IntPtr new_MyStaticClass();

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_delete_MyStaticClass")]
  public static extern void delete_MyStaticClass(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_Vector3Collection_Clear")]
  public static extern void Vector3Collection_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_Vector3Collection_Add")]
  public static extern void Vector3Collection_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_Vector3Collection_size")]
  public static extern uint Vector3Collection_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_Vector3Collection_capacity")]
  public static extern uint Vector3Collection_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_Vector3Collection_reserve")]
  public static extern void Vector3Collection_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_new_Vector3Collection__SWIG_0")]
  public static extern global::System.IntPtr new_Vector3Collection__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_new_Vector3Collection__SWIG_1")]
  public static extern global::System.IntPtr new_Vector3Collection__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_new_Vector3Collection__SWIG_2")]
  public static extern global::System.IntPtr new_Vector3Collection__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_Vector3Collection_getitemcopy")]
  public static extern global::System.IntPtr Vector3Collection_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_Vector3Collection_getitem")]
  public static extern global::System.IntPtr Vector3Collection_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_Vector3Collection_setitem")]
  public static extern void Vector3Collection_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_Vector3Collection_AddRange")]
  public static extern void Vector3Collection_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_Vector3Collection_GetRange")]
  public static extern global::System.IntPtr Vector3Collection_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_Vector3Collection_Insert")]
  public static extern void Vector3Collection_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_Vector3Collection_InsertRange")]
  public static extern void Vector3Collection_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_Vector3Collection_RemoveAt")]
  public static extern void Vector3Collection_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_Vector3Collection_RemoveRange")]
  public static extern void Vector3Collection_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_Vector3Collection_Repeat")]
  public static extern global::System.IntPtr Vector3Collection_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_Vector3Collection_Reverse__SWIG_0")]
  public static extern void Vector3Collection_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_Vector3Collection_Reverse__SWIG_1")]
  public static extern void Vector3Collection_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_Vector3Collection_SetRange")]
  public static extern void Vector3Collection_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_delete_Vector3Collection")]
  public static extern void delete_Vector3Collection(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_new_MyCppClass")]
  public static extern global::System.IntPtr new_MyCppClass();

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_delete_MyCppClass")]
  public static extern void delete_MyCppClass(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyCppClass_Add__SWIG_0")]
  public static extern double MyCppClass_Add__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyCppClass_CreateVector3")]
  public static extern global::System.IntPtr MyCppClass_CreateVector3(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyCppClass_Cross")]
  public static extern global::System.IntPtr MyCppClass_Cross(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyCppClass_Add__SWIG_1")]
  public static extern global::System.IntPtr MyCppClass_Add__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyCppClass_GetMyCollection")]
  public static extern global::System.IntPtr MyCppClass_GetMyCollection(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyCppClass_ShiftMyCollection")]
  public static extern global::System.IntPtr MyCppClass_ShiftMyCollection(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SWIG_Example", EntryPoint="CSharp_TomCpp_MyCppClass_ExpandMyCollection")]
  public static extern void MyCppClass_ExpandMyCollection(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);
}

}
