/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGCSHARP
#define SWIGCSHARP
#endif



#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_SWIG_Example(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_SWIG_Example(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_SWIG_Example(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else


#include <string>


#include <typeinfo>
#include <stdexcept>


#include <vector>
#include <algorithm>
#include <stdexcept>


#include "MyStaticClass.h"
#include "MyStruct.h"
#include "MyCppClass.h"	
using namespace Tom;
using namespace std;

SWIGINTERN std::vector< Tom::MyVector3 > *new_std_vector_Sl_Tom_MyVector3_Sg___SWIG_2(int capacity){
        std::vector< Tom::MyVector3 >* pv = 0;
        if (capacity >= 0) {
          pv = new std::vector< Tom::MyVector3 >();
          pv->reserve(capacity);
       } else {
          throw std::out_of_range("capacity");
       }
       return pv;
      }
SWIGINTERN Tom::MyVector3 std_vector_Sl_Tom_MyVector3_Sg__getitemcopy(std::vector< Tom::MyVector3 > *self,int index){
        if (index>=0 && index<(int)self->size())
          return (*self)[index];
        else
          throw std::out_of_range("index");
      }
SWIGINTERN std::vector< Tom::MyVector3 >::value_type const &std_vector_Sl_Tom_MyVector3_Sg__getitem(std::vector< Tom::MyVector3 > *self,int index){
        if (index>=0 && index<(int)self->size())
          return (*self)[index];
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Tom_MyVector3_Sg__setitem(std::vector< Tom::MyVector3 > *self,int index,Tom::MyVector3 const &val){
        if (index>=0 && index<(int)self->size())
          (*self)[index] = val;
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Tom_MyVector3_Sg__AddRange(std::vector< Tom::MyVector3 > *self,std::vector< Tom::MyVector3 > const &values){
        self->insert(self->end(), values.begin(), values.end());
      }
SWIGINTERN std::vector< Tom::MyVector3 > *std_vector_Sl_Tom_MyVector3_Sg__GetRange(std::vector< Tom::MyVector3 > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        return new std::vector< Tom::MyVector3 >(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN void std_vector_Sl_Tom_MyVector3_Sg__Insert(std::vector< Tom::MyVector3 > *self,int index,Tom::MyVector3 const &x){
        if (index>=0 && index<(int)self->size()+1)
          self->insert(self->begin()+index, x);
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Tom_MyVector3_Sg__InsertRange(std::vector< Tom::MyVector3 > *self,int index,std::vector< Tom::MyVector3 > const &values){
        if (index>=0 && index<(int)self->size()+1)
          self->insert(self->begin()+index, values.begin(), values.end());
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Tom_MyVector3_Sg__RemoveAt(std::vector< Tom::MyVector3 > *self,int index){
        if (index>=0 && index<(int)self->size())
          self->erase(self->begin() + index);
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Tom_MyVector3_Sg__RemoveRange(std::vector< Tom::MyVector3 > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        self->erase(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN std::vector< Tom::MyVector3 > *std_vector_Sl_Tom_MyVector3_Sg__Repeat(Tom::MyVector3 const &value,int count){
        if (count < 0)
          throw std::out_of_range("count");
        return new std::vector< Tom::MyVector3 >(count, value);
      }
SWIGINTERN void std_vector_Sl_Tom_MyVector3_Sg__Reverse__SWIG_0(std::vector< Tom::MyVector3 > *self){
        std::reverse(self->begin(), self->end());
      }
SWIGINTERN void std_vector_Sl_Tom_MyVector3_Sg__Reverse__SWIG_1(std::vector< Tom::MyVector3 > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        std::reverse(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN void std_vector_Sl_Tom_MyVector3_Sg__SetRange(std::vector< Tom::MyVector3 > *self,int index,std::vector< Tom::MyVector3 > const &values){
        if (index < 0)
          throw std::out_of_range("index");
        if (index+values.size() > self->size())
          throw std::out_of_range("index");
        std::copy(values.begin(), values.end(), self->begin()+index);
      }

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_MyVector3_X_set(void * jarg1, double jarg2) {
  Tom::MyVector3 *arg1 = (Tom::MyVector3 *) 0 ;
  double arg2 ;
  
  arg1 = (Tom::MyVector3 *)jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->X = arg2;
}


SWIGEXPORT double SWIGSTDCALL CSharp_TomCpp_MyVector3_X_get(void * jarg1) {
  double jresult ;
  Tom::MyVector3 *arg1 = (Tom::MyVector3 *) 0 ;
  double result;
  
  arg1 = (Tom::MyVector3 *)jarg1; 
  result = (double) ((arg1)->X);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_MyVector3_Y_set(void * jarg1, double jarg2) {
  Tom::MyVector3 *arg1 = (Tom::MyVector3 *) 0 ;
  double arg2 ;
  
  arg1 = (Tom::MyVector3 *)jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->Y = arg2;
}


SWIGEXPORT double SWIGSTDCALL CSharp_TomCpp_MyVector3_Y_get(void * jarg1) {
  double jresult ;
  Tom::MyVector3 *arg1 = (Tom::MyVector3 *) 0 ;
  double result;
  
  arg1 = (Tom::MyVector3 *)jarg1; 
  result = (double) ((arg1)->Y);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_MyVector3_Z_set(void * jarg1, double jarg2) {
  Tom::MyVector3 *arg1 = (Tom::MyVector3 *) 0 ;
  double arg2 ;
  
  arg1 = (Tom::MyVector3 *)jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->Z = arg2;
}


SWIGEXPORT double SWIGSTDCALL CSharp_TomCpp_MyVector3_Z_get(void * jarg1) {
  double jresult ;
  Tom::MyVector3 *arg1 = (Tom::MyVector3 *) 0 ;
  double result;
  
  arg1 = (Tom::MyVector3 *)jarg1; 
  result = (double) ((arg1)->Z);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TomCpp_new_MyVector3__SWIG_0() {
  void * jresult ;
  Tom::MyVector3 *result = 0 ;
  
  result = (Tom::MyVector3 *)new Tom::MyVector3();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TomCpp_new_MyVector3__SWIG_1(double jarg1, double jarg2, double jarg3) {
  void * jresult ;
  double arg1 ;
  double arg2 ;
  double arg3 ;
  Tom::MyVector3 *result = 0 ;
  
  arg1 = (double)jarg1; 
  arg2 = (double)jarg2; 
  arg3 = (double)jarg3; 
  result = (Tom::MyVector3 *)new Tom::MyVector3(arg1,arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_delete_MyVector3(void * jarg1) {
  Tom::MyVector3 *arg1 = (Tom::MyVector3 *) 0 ;
  
  arg1 = (Tom::MyVector3 *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_MyData_str_set(void * jarg1, char * jarg2) {
  Tom::MyData *arg1 = (Tom::MyData *) 0 ;
  std::string *arg2 = 0 ;
  
  arg1 = (Tom::MyData *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return ;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  if (arg1) (arg1)->str = *arg2;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_TomCpp_MyData_str_get(void * jarg1) {
  char * jresult ;
  Tom::MyData *arg1 = (Tom::MyData *) 0 ;
  std::string *result = 0 ;
  
  arg1 = (Tom::MyData *)jarg1; 
  result = (std::string *) & ((arg1)->str);
  jresult = SWIG_csharp_string_callback(result->c_str()); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_MyData_int16_set(void * jarg1, short jarg2) {
  Tom::MyData *arg1 = (Tom::MyData *) 0 ;
  short arg2 ;
  
  arg1 = (Tom::MyData *)jarg1; 
  arg2 = (short)jarg2; 
  if (arg1) (arg1)->int16 = arg2;
}


SWIGEXPORT short SWIGSTDCALL CSharp_TomCpp_MyData_int16_get(void * jarg1) {
  short jresult ;
  Tom::MyData *arg1 = (Tom::MyData *) 0 ;
  short result;
  
  arg1 = (Tom::MyData *)jarg1; 
  result = (short) ((arg1)->int16);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_MyData_int32_set(void * jarg1, int jarg2) {
  Tom::MyData *arg1 = (Tom::MyData *) 0 ;
  int arg2 ;
  
  arg1 = (Tom::MyData *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->int32 = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_TomCpp_MyData_int32_get(void * jarg1) {
  int jresult ;
  Tom::MyData *arg1 = (Tom::MyData *) 0 ;
  int result;
  
  arg1 = (Tom::MyData *)jarg1; 
  result = (int) ((arg1)->int32);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_MyData_singal_set(void * jarg1, float jarg2) {
  Tom::MyData *arg1 = (Tom::MyData *) 0 ;
  float arg2 ;
  
  arg1 = (Tom::MyData *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->singal = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_TomCpp_MyData_singal_get(void * jarg1) {
  float jresult ;
  Tom::MyData *arg1 = (Tom::MyData *) 0 ;
  float result;
  
  arg1 = (Tom::MyData *)jarg1; 
  result = (float) ((arg1)->singal);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TomCpp_new_MyData__SWIG_0() {
  void * jresult ;
  Tom::MyData *result = 0 ;
  
  result = (Tom::MyData *)new Tom::MyData();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TomCpp_new_MyData__SWIG_1(double jarg1, char * jarg2, short jarg3, int jarg4, float jarg5) {
  void * jresult ;
  double arg1 ;
  std::string arg2 ;
  short arg3 ;
  int arg4 ;
  float arg5 ;
  Tom::MyData *result = 0 ;
  
  arg1 = (double)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg2)->assign(jarg2); 
  arg3 = (short)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = (float)jarg5; 
  result = (Tom::MyData *)new Tom::MyData(arg1,arg2,arg3,arg4,arg5);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_delete_MyData(void * jarg1) {
  Tom::MyData *arg1 = (Tom::MyData *) 0 ;
  
  arg1 = (Tom::MyData *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_MyCoordinate_CoordinateString_set(void * jarg1, char * jarg2) {
  Tom::MyCoordinate *arg1 = (Tom::MyCoordinate *) 0 ;
  std::string *arg2 = 0 ;
  
  arg1 = (Tom::MyCoordinate *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return ;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  if (arg1) (arg1)->CoordinateString = *arg2;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_TomCpp_MyCoordinate_CoordinateString_get(void * jarg1) {
  char * jresult ;
  Tom::MyCoordinate *arg1 = (Tom::MyCoordinate *) 0 ;
  std::string *result = 0 ;
  
  arg1 = (Tom::MyCoordinate *)jarg1; 
  result = (std::string *) & ((arg1)->CoordinateString);
  jresult = SWIG_csharp_string_callback(result->c_str()); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_MyCoordinate_X_set(void * jarg1, void * jarg2) {
  Tom::MyCoordinate *arg1 = (Tom::MyCoordinate *) 0 ;
  Tom::MyVector3 *arg2 = (Tom::MyVector3 *) 0 ;
  
  arg1 = (Tom::MyCoordinate *)jarg1; 
  arg2 = (Tom::MyVector3 *)jarg2; 
  if (arg1) (arg1)->X = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TomCpp_MyCoordinate_X_get(void * jarg1) {
  void * jresult ;
  Tom::MyCoordinate *arg1 = (Tom::MyCoordinate *) 0 ;
  Tom::MyVector3 *result = 0 ;
  
  arg1 = (Tom::MyCoordinate *)jarg1; 
  result = (Tom::MyVector3 *)& ((arg1)->X);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_MyCoordinate_Y_set(void * jarg1, void * jarg2) {
  Tom::MyCoordinate *arg1 = (Tom::MyCoordinate *) 0 ;
  Tom::MyVector3 *arg2 = (Tom::MyVector3 *) 0 ;
  
  arg1 = (Tom::MyCoordinate *)jarg1; 
  arg2 = (Tom::MyVector3 *)jarg2; 
  if (arg1) (arg1)->Y = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TomCpp_MyCoordinate_Y_get(void * jarg1) {
  void * jresult ;
  Tom::MyCoordinate *arg1 = (Tom::MyCoordinate *) 0 ;
  Tom::MyVector3 *result = 0 ;
  
  arg1 = (Tom::MyCoordinate *)jarg1; 
  result = (Tom::MyVector3 *)& ((arg1)->Y);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_MyCoordinate_Z_set(void * jarg1, void * jarg2) {
  Tom::MyCoordinate *arg1 = (Tom::MyCoordinate *) 0 ;
  Tom::MyVector3 *arg2 = (Tom::MyVector3 *) 0 ;
  
  arg1 = (Tom::MyCoordinate *)jarg1; 
  arg2 = (Tom::MyVector3 *)jarg2; 
  if (arg1) (arg1)->Z = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TomCpp_MyCoordinate_Z_get(void * jarg1) {
  void * jresult ;
  Tom::MyCoordinate *arg1 = (Tom::MyCoordinate *) 0 ;
  Tom::MyVector3 *result = 0 ;
  
  arg1 = (Tom::MyCoordinate *)jarg1; 
  result = (Tom::MyVector3 *)& ((arg1)->Z);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TomCpp_new_MyCoordinate__SWIG_0() {
  void * jresult ;
  Tom::MyCoordinate *result = 0 ;
  
  result = (Tom::MyCoordinate *)new Tom::MyCoordinate();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TomCpp_new_MyCoordinate__SWIG_1(void * jarg1, void * jarg2, void * jarg3) {
  void * jresult ;
  Tom::MyVector3 arg1 ;
  Tom::MyVector3 arg2 ;
  Tom::MyVector3 arg3 ;
  Tom::MyVector3 *argp1 ;
  Tom::MyVector3 *argp2 ;
  Tom::MyVector3 *argp3 ;
  Tom::MyCoordinate *result = 0 ;
  
  argp1 = (Tom::MyVector3 *)jarg1; 
  if (!argp1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null Tom::MyVector3", 0);
    return 0;
  }
  arg1 = *argp1; 
  argp2 = (Tom::MyVector3 *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null Tom::MyVector3", 0);
    return 0;
  }
  arg2 = *argp2; 
  argp3 = (Tom::MyVector3 *)jarg3; 
  if (!argp3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null Tom::MyVector3", 0);
    return 0;
  }
  arg3 = *argp3; 
  result = (Tom::MyCoordinate *)new Tom::MyCoordinate(arg1,arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_delete_MyCoordinate(void * jarg1) {
  Tom::MyCoordinate *arg1 = (Tom::MyCoordinate *) 0 ;
  
  arg1 = (Tom::MyCoordinate *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_MyStaticClass_ShowMessage(char * jarg1) {
  std::string arg1 ;
  
  if (!jarg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return ;
  }
  (&arg1)->assign(jarg1); 
  Tom::MyStaticClass::ShowMessage(arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TomCpp_new_MyStaticClass() {
  void * jresult ;
  Tom::MyStaticClass *result = 0 ;
  
  result = (Tom::MyStaticClass *)new Tom::MyStaticClass();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_delete_MyStaticClass(void * jarg1) {
  Tom::MyStaticClass *arg1 = (Tom::MyStaticClass *) 0 ;
  
  arg1 = (Tom::MyStaticClass *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_Vector3Collection_Clear(void * jarg1) {
  std::vector< Tom::MyVector3 > *arg1 = (std::vector< Tom::MyVector3 > *) 0 ;
  
  arg1 = (std::vector< Tom::MyVector3 > *)jarg1; 
  (arg1)->clear();
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_Vector3Collection_Add(void * jarg1, void * jarg2) {
  std::vector< Tom::MyVector3 > *arg1 = (std::vector< Tom::MyVector3 > *) 0 ;
  Tom::MyVector3 *arg2 = 0 ;
  
  arg1 = (std::vector< Tom::MyVector3 > *)jarg1; 
  arg2 = (Tom::MyVector3 *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Tom::MyVector3 const & type is null", 0);
    return ;
  } 
  (arg1)->push_back((Tom::MyVector3 const &)*arg2);
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_TomCpp_Vector3Collection_size(void * jarg1) {
  unsigned long jresult ;
  std::vector< Tom::MyVector3 > *arg1 = (std::vector< Tom::MyVector3 > *) 0 ;
  std::vector< Tom::MyVector3 >::size_type result;
  
  arg1 = (std::vector< Tom::MyVector3 > *)jarg1; 
  result = ((std::vector< Tom::MyVector3 > const *)arg1)->size();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_TomCpp_Vector3Collection_capacity(void * jarg1) {
  unsigned long jresult ;
  std::vector< Tom::MyVector3 > *arg1 = (std::vector< Tom::MyVector3 > *) 0 ;
  std::vector< Tom::MyVector3 >::size_type result;
  
  arg1 = (std::vector< Tom::MyVector3 > *)jarg1; 
  result = ((std::vector< Tom::MyVector3 > const *)arg1)->capacity();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_Vector3Collection_reserve(void * jarg1, unsigned long jarg2) {
  std::vector< Tom::MyVector3 > *arg1 = (std::vector< Tom::MyVector3 > *) 0 ;
  std::vector< Tom::MyVector3 >::size_type arg2 ;
  
  arg1 = (std::vector< Tom::MyVector3 > *)jarg1; 
  arg2 = (std::vector< Tom::MyVector3 >::size_type)jarg2; 
  (arg1)->reserve(arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TomCpp_new_Vector3Collection__SWIG_0() {
  void * jresult ;
  std::vector< Tom::MyVector3 > *result = 0 ;
  
  result = (std::vector< Tom::MyVector3 > *)new std::vector< Tom::MyVector3 >();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TomCpp_new_Vector3Collection__SWIG_1(void * jarg1) {
  void * jresult ;
  std::vector< Tom::MyVector3 > *arg1 = 0 ;
  std::vector< Tom::MyVector3 > *result = 0 ;
  
  arg1 = (std::vector< Tom::MyVector3 > *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Tom::MyVector3 > const & type is null", 0);
    return 0;
  } 
  result = (std::vector< Tom::MyVector3 > *)new std::vector< Tom::MyVector3 >((std::vector< Tom::MyVector3 > const &)*arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TomCpp_new_Vector3Collection__SWIG_2(int jarg1) {
  void * jresult ;
  int arg1 ;
  std::vector< Tom::MyVector3 > *result = 0 ;
  
  arg1 = (int)jarg1; 
  try {
    result = (std::vector< Tom::MyVector3 > *)new_std_vector_Sl_Tom_MyVector3_Sg___SWIG_2(arg1);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TomCpp_Vector3Collection_getitemcopy(void * jarg1, int jarg2) {
  void * jresult ;
  std::vector< Tom::MyVector3 > *arg1 = (std::vector< Tom::MyVector3 > *) 0 ;
  int arg2 ;
  Tom::MyVector3 result;
  
  arg1 = (std::vector< Tom::MyVector3 > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = std_vector_Sl_Tom_MyVector3_Sg__getitemcopy(arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = new Tom::MyVector3((const Tom::MyVector3 &)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TomCpp_Vector3Collection_getitem(void * jarg1, int jarg2) {
  void * jresult ;
  std::vector< Tom::MyVector3 > *arg1 = (std::vector< Tom::MyVector3 > *) 0 ;
  int arg2 ;
  std::vector< Tom::MyVector3 >::value_type *result = 0 ;
  
  arg1 = (std::vector< Tom::MyVector3 > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< Tom::MyVector3 >::value_type *) &std_vector_Sl_Tom_MyVector3_Sg__getitem(arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_Vector3Collection_setitem(void * jarg1, int jarg2, void * jarg3) {
  std::vector< Tom::MyVector3 > *arg1 = (std::vector< Tom::MyVector3 > *) 0 ;
  int arg2 ;
  Tom::MyVector3 *arg3 = 0 ;
  
  arg1 = (std::vector< Tom::MyVector3 > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (Tom::MyVector3 *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Tom::MyVector3 const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_Tom_MyVector3_Sg__setitem(arg1,arg2,(Tom::MyVector3 const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_Vector3Collection_AddRange(void * jarg1, void * jarg2) {
  std::vector< Tom::MyVector3 > *arg1 = (std::vector< Tom::MyVector3 > *) 0 ;
  std::vector< Tom::MyVector3 > *arg2 = 0 ;
  
  arg1 = (std::vector< Tom::MyVector3 > *)jarg1; 
  arg2 = (std::vector< Tom::MyVector3 > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Tom::MyVector3 > const & type is null", 0);
    return ;
  } 
  std_vector_Sl_Tom_MyVector3_Sg__AddRange(arg1,(std::vector< Tom::MyVector3 > const &)*arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TomCpp_Vector3Collection_GetRange(void * jarg1, int jarg2, int jarg3) {
  void * jresult ;
  std::vector< Tom::MyVector3 > *arg1 = (std::vector< Tom::MyVector3 > *) 0 ;
  int arg2 ;
  int arg3 ;
  std::vector< Tom::MyVector3 > *result = 0 ;
  
  arg1 = (std::vector< Tom::MyVector3 > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    result = (std::vector< Tom::MyVector3 > *)std_vector_Sl_Tom_MyVector3_Sg__GetRange(arg1,arg2,arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  } catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return 0;
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_Vector3Collection_Insert(void * jarg1, int jarg2, void * jarg3) {
  std::vector< Tom::MyVector3 > *arg1 = (std::vector< Tom::MyVector3 > *) 0 ;
  int arg2 ;
  Tom::MyVector3 *arg3 = 0 ;
  
  arg1 = (std::vector< Tom::MyVector3 > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (Tom::MyVector3 *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Tom::MyVector3 const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_Tom_MyVector3_Sg__Insert(arg1,arg2,(Tom::MyVector3 const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_Vector3Collection_InsertRange(void * jarg1, int jarg2, void * jarg3) {
  std::vector< Tom::MyVector3 > *arg1 = (std::vector< Tom::MyVector3 > *) 0 ;
  int arg2 ;
  std::vector< Tom::MyVector3 > *arg3 = 0 ;
  
  arg1 = (std::vector< Tom::MyVector3 > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (std::vector< Tom::MyVector3 > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Tom::MyVector3 > const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_Tom_MyVector3_Sg__InsertRange(arg1,arg2,(std::vector< Tom::MyVector3 > const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_Vector3Collection_RemoveAt(void * jarg1, int jarg2) {
  std::vector< Tom::MyVector3 > *arg1 = (std::vector< Tom::MyVector3 > *) 0 ;
  int arg2 ;
  
  arg1 = (std::vector< Tom::MyVector3 > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    std_vector_Sl_Tom_MyVector3_Sg__RemoveAt(arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_Vector3Collection_RemoveRange(void * jarg1, int jarg2, int jarg3) {
  std::vector< Tom::MyVector3 > *arg1 = (std::vector< Tom::MyVector3 > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (std::vector< Tom::MyVector3 > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    std_vector_Sl_Tom_MyVector3_Sg__RemoveRange(arg1,arg2,arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  } catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return ;
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TomCpp_Vector3Collection_Repeat(void * jarg1, int jarg2) {
  void * jresult ;
  Tom::MyVector3 *arg1 = 0 ;
  int arg2 ;
  std::vector< Tom::MyVector3 > *result = 0 ;
  
  arg1 = (Tom::MyVector3 *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Tom::MyVector3 const & type is null", 0);
    return 0;
  } 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< Tom::MyVector3 > *)std_vector_Sl_Tom_MyVector3_Sg__Repeat((Tom::MyVector3 const &)*arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_Vector3Collection_Reverse__SWIG_0(void * jarg1) {
  std::vector< Tom::MyVector3 > *arg1 = (std::vector< Tom::MyVector3 > *) 0 ;
  
  arg1 = (std::vector< Tom::MyVector3 > *)jarg1; 
  std_vector_Sl_Tom_MyVector3_Sg__Reverse__SWIG_0(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_Vector3Collection_Reverse__SWIG_1(void * jarg1, int jarg2, int jarg3) {
  std::vector< Tom::MyVector3 > *arg1 = (std::vector< Tom::MyVector3 > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (std::vector< Tom::MyVector3 > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    std_vector_Sl_Tom_MyVector3_Sg__Reverse__SWIG_1(arg1,arg2,arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  } catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_Vector3Collection_SetRange(void * jarg1, int jarg2, void * jarg3) {
  std::vector< Tom::MyVector3 > *arg1 = (std::vector< Tom::MyVector3 > *) 0 ;
  int arg2 ;
  std::vector< Tom::MyVector3 > *arg3 = 0 ;
  
  arg1 = (std::vector< Tom::MyVector3 > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (std::vector< Tom::MyVector3 > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Tom::MyVector3 > const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_Tom_MyVector3_Sg__SetRange(arg1,arg2,(std::vector< Tom::MyVector3 > const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_delete_Vector3Collection(void * jarg1) {
  std::vector< Tom::MyVector3 > *arg1 = (std::vector< Tom::MyVector3 > *) 0 ;
  
  arg1 = (std::vector< Tom::MyVector3 > *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TomCpp_new_MyCppClass() {
  void * jresult ;
  Tom::MyCppClass *result = 0 ;
  
  result = (Tom::MyCppClass *)new Tom::MyCppClass();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_delete_MyCppClass(void * jarg1) {
  Tom::MyCppClass *arg1 = (Tom::MyCppClass *) 0 ;
  
  arg1 = (Tom::MyCppClass *)jarg1; 
  delete arg1;
}


SWIGEXPORT double SWIGSTDCALL CSharp_TomCpp_MyCppClass_Add__SWIG_0(void * jarg1, double jarg2, double jarg3) {
  double jresult ;
  Tom::MyCppClass *arg1 = (Tom::MyCppClass *) 0 ;
  double arg2 ;
  double arg3 ;
  double result;
  
  arg1 = (Tom::MyCppClass *)jarg1; 
  arg2 = (double)jarg2; 
  arg3 = (double)jarg3; 
  result = (double)(arg1)->Add(arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TomCpp_MyCppClass_CreateVector3(void * jarg1) {
  void * jresult ;
  Tom::MyCppClass *arg1 = (Tom::MyCppClass *) 0 ;
  Tom::MyVector3 result;
  
  arg1 = (Tom::MyCppClass *)jarg1; 
  result = (arg1)->CreateVector3();
  jresult = new Tom::MyVector3((const Tom::MyVector3 &)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TomCpp_MyCppClass_Cross(void * jarg1, void * jarg2, void * jarg3) {
  void * jresult ;
  Tom::MyCppClass *arg1 = (Tom::MyCppClass *) 0 ;
  Tom::MyVector3 arg2 ;
  Tom::MyVector3 arg3 ;
  Tom::MyVector3 *argp2 ;
  Tom::MyVector3 *argp3 ;
  Tom::MyVector3 result;
  
  arg1 = (Tom::MyCppClass *)jarg1; 
  argp2 = (Tom::MyVector3 *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null Tom::MyVector3", 0);
    return 0;
  }
  arg2 = *argp2; 
  argp3 = (Tom::MyVector3 *)jarg3; 
  if (!argp3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null Tom::MyVector3", 0);
    return 0;
  }
  arg3 = *argp3; 
  result = (arg1)->Cross(arg2,arg3);
  jresult = new Tom::MyVector3((const Tom::MyVector3 &)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TomCpp_MyCppClass_Add__SWIG_1(void * jarg1, void * jarg2, void * jarg3) {
  void * jresult ;
  Tom::MyCppClass *arg1 = (Tom::MyCppClass *) 0 ;
  Tom::MyVector3 arg2 ;
  Tom::MyVector3 arg3 ;
  Tom::MyVector3 *argp2 ;
  Tom::MyVector3 *argp3 ;
  Tom::MyVector3 result;
  
  arg1 = (Tom::MyCppClass *)jarg1; 
  argp2 = (Tom::MyVector3 *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null Tom::MyVector3", 0);
    return 0;
  }
  arg2 = *argp2; 
  argp3 = (Tom::MyVector3 *)jarg3; 
  if (!argp3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null Tom::MyVector3", 0);
    return 0;
  }
  arg3 = *argp3; 
  result = (arg1)->Add(arg2,arg3);
  jresult = new Tom::MyVector3((const Tom::MyVector3 &)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TomCpp_MyCppClass_GetMyCollection(void * jarg1) {
  void * jresult ;
  Tom::MyCppClass *arg1 = (Tom::MyCppClass *) 0 ;
  std::vector< Tom::MyVector3 > result;
  
  arg1 = (Tom::MyCppClass *)jarg1; 
  result = (arg1)->GetMyCollection();
  jresult = new std::vector< Tom::MyVector3 >((const std::vector< Tom::MyVector3 > &)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TomCpp_MyCppClass_ShiftMyCollection(void * jarg1, void * jarg2) {
  void * jresult ;
  Tom::MyCppClass *arg1 = (Tom::MyCppClass *) 0 ;
  std::vector< Tom::MyVector3 > arg2 ;
  std::vector< Tom::MyVector3 > *argp2 ;
  std::vector< Tom::MyVector3 > result;
  
  arg1 = (Tom::MyCppClass *)jarg1; 
  argp2 = (std::vector< Tom::MyVector3 > *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null std::vector< Tom::MyVector3 >", 0);
    return 0;
  }
  arg2 = *argp2; 
  result = (arg1)->ShiftMyCollection(arg2);
  jresult = new std::vector< Tom::MyVector3 >((const std::vector< Tom::MyVector3 > &)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TomCpp_MyCppClass_ExpandMyCollection(void * jarg1, void * jarg2) {
  Tom::MyCppClass *arg1 = (Tom::MyCppClass *) 0 ;
  std::vector< Tom::MyVector3 > *arg2 = 0 ;
  
  arg1 = (Tom::MyCppClass *)jarg1; 
  arg2 = (std::vector< Tom::MyVector3 > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Tom::MyVector3 > & type is null", 0);
    return ;
  } 
  (arg1)->ExpandMyCollection(*arg2);
}


#ifdef __cplusplus
}
#endif

